# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sync_gui.ui'
#
# Created: Thu Jul 28 19:24:18 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(785, 619)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("res/record.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit_output_path = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_output_path.setObjectName(_fromUtf8("lineEdit_output_path"))
        self.gridLayout_2.addWidget(self.lineEdit_output_path, 0, 3, 1, 1)
        self.checkBox_timestamp = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_timestamp.setChecked(True)
        self.checkBox_timestamp.setObjectName(_fromUtf8("checkBox_timestamp"))
        self.gridLayout_2.addWidget(self.checkBox_timestamp, 0, 4, 1, 1)
        self.checkBox_comm = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_comm.setObjectName(_fromUtf8("checkBox_comm"))
        self.gridLayout_2.addWidget(self.checkBox_comm, 1, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.digital = QtGui.QWidget()
        self.digital.setObjectName(_fromUtf8("digital"))
        self.gridLayout_4 = QtGui.QGridLayout(self.digital)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.digital)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_freq = QtGui.QLabel(self.groupBox)
        self.label_freq.setObjectName(_fromUtf8("label_freq"))
        self.gridLayout.addWidget(self.label_freq, 1, 0, 1, 1)
        self.lineEdit_pulse_freq = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_pulse_freq.setObjectName(_fromUtf8("lineEdit_pulse_freq"))
        self.gridLayout.addWidget(self.lineEdit_pulse_freq, 1, 2, 1, 1)
        self.label_rollover = QtGui.QLabel(self.groupBox)
        self.label_rollover.setObjectName(_fromUtf8("label_rollover"))
        self.gridLayout.addWidget(self.label_rollover, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_data_bits = QtGui.QLabel(self.groupBox)
        self.label_data_bits.setObjectName(_fromUtf8("label_data_bits"))
        self.gridLayout.addWidget(self.label_data_bits, 0, 0, 1, 1)
        self.lineEdit_data_bits = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_data_bits.setObjectName(_fromUtf8("lineEdit_data_bits"))
        self.gridLayout.addWidget(self.lineEdit_data_bits, 0, 2, 1, 1)
        self.comboBox_device = QtGui.QComboBox(self.groupBox)
        self.comboBox_device.setObjectName(_fromUtf8("comboBox_device"))
        self.gridLayout.addWidget(self.comboBox_device, 2, 2, 1, 1)
        self.label_device_model = QtGui.QLabel(self.groupBox)
        self.label_device_model.setText(_fromUtf8(""))
        self.label_device_model.setObjectName(_fromUtf8("label_device_model"))
        self.gridLayout.addWidget(self.label_device_model, 2, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.digital, _fromUtf8(""))
        self.analog = QtGui.QWidget()
        self.analog.setObjectName(_fromUtf8("analog"))
        self.gridLayout_5 = QtGui.QGridLayout(self.analog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_analog = QtGui.QGroupBox(self.analog)
        self.groupBox_analog.setTitle(_fromUtf8(""))
        self.groupBox_analog.setObjectName(_fromUtf8("groupBox_analog"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_analog)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.checkBox_analog_channels = QtGui.QCheckBox(self.groupBox_analog)
        self.checkBox_analog_channels.setObjectName(_fromUtf8("checkBox_analog_channels"))
        self.gridLayout_6.addWidget(self.checkBox_analog_channels, 0, 0, 1, 1)
        self.comboBox_analog_freq = QtGui.QComboBox(self.groupBox_analog)
        self.comboBox_analog_freq.setObjectName(_fromUtf8("comboBox_analog_freq"))
        self.comboBox_analog_freq.addItem(_fromUtf8(""))
        self.comboBox_analog_freq.addItem(_fromUtf8(""))
        self.comboBox_analog_freq.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_analog_freq, 1, 0, 1, 1)
        self.comboBox_dtype = QtGui.QComboBox(self.groupBox_analog)
        self.comboBox_dtype.setObjectName(_fromUtf8("comboBox_dtype"))
        self.comboBox_dtype.addItem(_fromUtf8(""))
        self.comboBox_dtype.addItem(_fromUtf8(""))
        self.comboBox_dtype.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_dtype, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_analog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_dtype = QtGui.QLabel(self.groupBox_analog)
        self.label_dtype.setObjectName(_fromUtf8("label_dtype"))
        self.gridLayout_6.addWidget(self.label_dtype, 1, 3, 1, 1)
        self.lineEdit_analog_channels = QtGui.QLineEdit(self.groupBox_analog)
        self.lineEdit_analog_channels.setObjectName(_fromUtf8("lineEdit_analog_channels"))
        self.gridLayout_6.addWidget(self.lineEdit_analog_channels, 0, 1, 1, 4)
        self.label_datarate = QtGui.QLabel(self.groupBox_analog)
        self.label_datarate.setObjectName(_fromUtf8("label_datarate"))
        self.gridLayout_6.addWidget(self.label_datarate, 1, 4, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_analog, 1, 0, 1, 1)
        self.tabWidget.addTab(self.analog, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox_ci = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_ci.setEnabled(False)
        self.comboBox_ci.setObjectName(_fromUtf8("comboBox_ci"))
        self.gridLayout_7.addWidget(self.comboBox_ci, 1, 0, 1, 1)
        self.checkBox_ci = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_ci.setObjectName(_fromUtf8("checkBox_ci"))
        self.gridLayout_7.addWidget(self.checkBox_ci, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.checkBox_co = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_co.setObjectName(_fromUtf8("checkBox_co"))
        self.gridLayout_8.addWidget(self.checkBox_co, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 2, 2, 1, 3)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_2.addWidget(self.plainTextEdit, 5, 2, 1, 3)
        self.pushButton_start = QtGui.QPushButton(self.centralwidget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(200, 150))
        self.pushButton_start.setText(_fromUtf8(""))
        self.pushButton_start.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.gridLayout_2.addWidget(self.pushButton_start, 3, 2, 1, 2)
        self.pushButton_visualize = QtGui.QPushButton(self.centralwidget)
        self.pushButton_visualize.setMinimumSize(QtCore.QSize(150, 150))
        self.pushButton_visualize.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("res/visualizer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_visualize.setIcon(icon1)
        self.pushButton_visualize.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_visualize.setObjectName(_fromUtf8("pushButton_visualize"))
        self.gridLayout_2.addWidget(self.pushButton_visualize, 3, 4, 1, 1)
        self.tableWidget_labels = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_labels.setMinimumSize(QtCore.QSize(150, 0))
        self.tableWidget_labels.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableWidget_labels.setShowGrid(True)
        self.tableWidget_labels.setGridStyle(QtCore.Qt.DashDotLine)
        self.tableWidget_labels.setCornerButtonEnabled(True)
        self.tableWidget_labels.setRowCount(32)
        self.tableWidget_labels.setColumnCount(1)
        self.tableWidget_labels.setObjectName(_fromUtf8("tableWidget_labels"))
        self.tableWidget_labels.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_labels.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_2.addWidget(self.tableWidget_labels, 0, 0, 6, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sync", None))
        self.label.setText(_translate("MainWindow", "Output path:", None))
        self.lineEdit_output_path.setText(_translate("MainWindow", "C:/sync/output/test", None))
        self.checkBox_timestamp.setText(_translate("MainWindow", "Timestamp", None))
        self.checkBox_comm.setText(_translate("MainWindow", "Remote Control", None))
        self.label_freq.setText(_translate("MainWindow", "Sample Freq (Hz):", None))
        self.lineEdit_pulse_freq.setText(_translate("MainWindow", "100000.0", None))
        self.label_rollover.setText(_translate("MainWindow", "Rollover", None))
        self.label_5.setText(_translate("MainWindow", "Device:", None))
        self.label_data_bits.setText(_translate("MainWindow", "Digital lines:", None))
        self.lineEdit_data_bits.setText(_translate("MainWindow", "32", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.digital), _translate("MainWindow", "Digital", None))
        self.checkBox_analog_channels.setText(_translate("MainWindow", "Channels:", None))
        self.comboBox_analog_freq.setItemText(0, _translate("MainWindow", "1000", None))
        self.comboBox_analog_freq.setItemText(1, _translate("MainWindow", "10000", None))
        self.comboBox_analog_freq.setItemText(2, _translate("MainWindow", "20000", None))
        self.comboBox_dtype.setItemText(0, _translate("MainWindow", "64", None))
        self.comboBox_dtype.setItemText(1, _translate("MainWindow", "32", None))
        self.comboBox_dtype.setItemText(2, _translate("MainWindow", "16", None))
        self.label_2.setText(_translate("MainWindow", "Hz", None))
        self.label_dtype.setText(_translate("MainWindow", "bit", None))
        self.lineEdit_analog_channels.setText(_translate("MainWindow", "[0,1]", None))
        self.label_datarate.setText(_translate("MainWindow", "??? MB/hr", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analog), _translate("MainWindow", "Analog", None))
        self.checkBox_ci.setText(_translate("MainWindow", "Counter Input", None))
        self.checkBox_co.setText(_translate("MainWindow", "Counter Output", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Counter", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

